// Package main demonstrates a Thrift RPC server using the EchoService defined
// in the testing/api/thrift IDL, with recovery and logging processor wrappers.
//
// Unlike HTTP/GraphQL, Thrift is a binary RPC protocol that does not use
// net/http, so HTTP middleware cannot be reused. Instead, cross-cutting
// concerns are handled via Processor Wrappers that compose thrift.TProcessor.
//
// The server uses binary protocol (default) and listens on port 7700.
// A built-in client is started in a goroutine to demonstrate the round-trip.
//
// Run:
//
//	go run ./examples/thrift-basic
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/apache/thrift/lib/go/thrift"

	echo "github.com/tx7do/go-wind-plugins/testing/api/thrift/gen-go/echo"
	thriftServer "github.com/tx7do/go-wind-plugins/transport/thrift"
)

// echoHandler implements the echo.EchoService interface generated by the Thrift compiler.
type echoHandler struct{}

// Echo returns the same message it receives.
func (h *echoHandler) Echo(_ context.Context, req *echo.Request) (*echo.Response, error) {
	fmt.Printf("[Echo] received: %s\n", req.GetMsg())
	return &echo.Response{Msg: "echo: " + req.GetMsg()}, nil
}

// VisitOneway handles a one-way (fire-and-forget) call.
func (h *echoHandler) VisitOneway(_ context.Context, req *echo.Request) error {
	fmt.Printf("[VisitOneway] received: %s (no response)\n", req.GetMsg())
	return nil
}

func main() {
	processor := echo.NewEchoServiceProcessor(&echoHandler{})

	// ── Processor Wrappers ──────────────────────────────────────────
	// Thrift doesn't run over HTTP, so HTTP middleware cannot be used.
	// Instead, cross-cutting concerns are applied via Processor Wrappers.
	// The first wrapper is outermost (runs first on the way in).
	srv := thriftServer.NewServer(":7700",
		thriftServer.WithProcessor(processor),
		thriftServer.WithProtocol("binary"),
		thriftServer.WithRecovery(nil), // outermost: catches panics in handlers
		thriftServer.WithLogging(nil),  // logs every RPC call with duration
	)

	// Graceful shutdown on signal.
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	// Start the server in a goroutine, then run a quick client demo.
	go func() {
		time.Sleep(500 * time.Millisecond) // wait for server to be ready

		socket := thrift.NewTSocketConf("127.0.0.1:7700", nil)
		defer socket.Close()

		transport, err := thrift.NewTBufferedTransportFactory(8192).GetTransport(socket)
		if err != nil {
			fmt.Fprintf(os.Stderr, "client transport failed: %v\n", err)
			return
		}
		if err := transport.Open(); err != nil {
			fmt.Fprintf(os.Stderr, "client open failed: %v\n", err)
			return
		}
		defer transport.Close()

		protoFactory := thrift.NewTBinaryProtocolFactoryConf(nil)
		client := echo.NewEchoServiceClientFactory(transport, protoFactory)

		// Ping-pong call.
		resp, err := client.Echo(context.Background(), &echo.Request{Msg: "Hello Thrift!"})
		if err != nil {
			fmt.Fprintf(os.Stderr, "Echo failed: %v\n", err)
			return
		}
		fmt.Printf("[Client] Echo response: %s\n", resp.GetMsg())

		// One-way call.
		if err := client.VisitOneway(context.Background(), &echo.Request{Msg: "goodbye"}); err != nil {
			fmt.Fprintf(os.Stderr, "VisitOneway failed: %v\n", err)
		}

		// Demo done, trigger shutdown.
		fmt.Println("[Client] demo finished, shutting down server...")
		stop()
	}()

	fmt.Printf("Thrift server listening on %s\n", srv.Endpoint())
	if err := srv.Start(ctx); err != nil {
		fmt.Fprintf(os.Stderr, "server error: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("server stopped")
}
