// Package main demonstrates a minimal gRPC server using the go-wind framework
// with a recovery + logging interceptor chain.
//
// To keep this example self-contained (no .proto files, no protoc), we manually
// construct a grpc.ServiceDesc for a simple Echo service. In a real project,
// the ServiceDesc is generated by protoc-gen-go-grpc.
//
// Run:
//
//	go run ./examples/grpc-basic
//
// Test with grpcurl:
//
//	grpcurl -plaintext -d '{"message":"hello"}' localhost:9000 echo.EchoService/Say
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/tx7do/go-wind-plugins/transport/grpc/middleware/logging"
	grpcRecovery "github.com/tx7do/go-wind-plugins/transport/grpc/middleware/recovery"
	grpcServer "github.com/tx7do/go-wind-plugins/transport/grpc/server"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// ---------------------------------------------------------------------------
// Echo service — no .proto needed, manually defined
// ---------------------------------------------------------------------------

// EchoRequest / EchoResponse use protobuf field numbering via struct tags.
// They work with gRPC's default proto codec.
type EchoRequest struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *EchoRequest) Reset()         { *m = EchoRequest{} }
func (m *EchoRequest) String() string { return fmt.Sprintf("{message:%q}", m.Message) }
func (m *EchoRequest) ProtoMessage()  {}

type EchoResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *EchoResponse) Reset()         { *m = EchoResponse{} }
func (m *EchoResponse) String() string { return fmt.Sprintf("{message:%q}", m.Message) }
func (m *EchoResponse) ProtoMessage()  {}

// echoServiceImpl implements the Echo service.
type echoServiceImpl struct{}

// Say echoes the incoming message back to the client.
func (s *echoServiceImpl) Say(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	if req.Message == "" {
		return nil, status.Error(codes.InvalidArgument, "message is required")
	}
	return &EchoResponse{Message: "echo: " + req.Message}, nil
}

// _echoSayHandler is the grpc.UnaryHandler signature adapted to our typed method.
func _echoSayHandler(srv any, ctx context.Context, dec func(any) error, _ grpc.UnaryServerInterceptor) (any, error) {
	req := &EchoRequest{}
	if err := dec(req); err != nil {
		return nil, status.Error(codes.InvalidArgument, err.Error())
	}
	return srv.(*echoServiceImpl).Say(ctx, req)
}

// echoServiceDesc is a manually-constructed service descriptor.
// In a real project, protoc-gen-go-grpc generates this automatically.
var echoServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.EchoService",
	HandlerType: (*echoServiceImpl)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Say",
			Handler:    _echoSayHandler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "echo.proto",
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

func main() {
	srv := grpcServer.NewServer(":9000",
		grpcServer.WithMiddleware(
			grpcRecovery.UnaryInterceptor(),
			logging.UnaryInterceptor(),
		),
	)

	// Register our echo service.
	srv.RegisterService(&echoServiceDesc, &echoServiceImpl{})

	// Graceful shutdown.
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	fmt.Printf("gRPC server listening on %s\n", srv.Endpoint())
	if err := srv.Start(ctx); err != nil {
		fmt.Fprintf(os.Stderr, "server error: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("server stopped")
}
