package flatbuffers_test

import (
	"fmt"

	fb "github.com/google/flatbuffers/go"

	"github.com/tx7do/go-wind-plugins/encoding"
	"github.com/tx7do/go-wind-plugins/encoding/flatbuffers"
)

// sampleEntity stands in for a builder-side type generated by the flatc
// compiler: it implements flatbuffers.FlatBufferMarshaler by packing a
// single string field into a buffer with the Builder API, the way
// generated Pack methods do.
type sampleEntity struct {
	name string
}

func (e *sampleEntity) PackFlatBuffer() ([]byte, error) {
	b := fb.NewBuilder(0)
	name := b.CreateString(e.name)
	b.StartObject(1)
	b.PrependUOffsetTSlot(0, name, 0)
	root := b.EndObject()
	b.Finish(root)
	return b.FinishedBytes(), nil
}

// sampleTable stands in for an accessor type generated by the flatc
// compiler: it implements the flatbuffers.FlatBuffer interface and reads
// the one field packed above through a zero-copy view of the buffer.
type sampleTable struct {
	tab fb.Table
}

func (t *sampleTable) Init(buf []byte, i fb.UOffsetT) {
	t.tab = fb.Table{
		Bytes: buf,
		Pos:   i,
	}
}

func (t *sampleTable) Table() fb.Table { return t.tab }

// Name reads the string stored in slot 0 (vtable offset 4).
func (t *sampleTable) Name() string {
	o := fb.UOffsetT(t.tab.Offset(4))
	if o != 0 {
		return t.tab.String(o + t.tab.Pos)
	}
	return ""
}

// Example resolves the FlatBuffers codec through the shared codec registry
// and round-trips a buffer through it. FlatBuffers skips reflection
// entirely: the producer hands over a packed buffer and the consumer reads
// it back through a generated table view, with both roles played here by
// the sample types above.
func Example() {
	codec := encoding.GetCodec(flatbuffers.Name)
	if codec == nil {
		return
	}

	encoded, err := codec.Marshal(&sampleEntity{name: "hello"})
	if err != nil {
		return
	}

	decoded := &sampleTable{}
	if err := codec.Unmarshal(encoded, decoded); err != nil {
		return
	}

	fmt.Println(decoded.Name())
	// Output: hello
}
