// Package flatbuffers provides a [encoding.Codec] implementation using
// Google FlatBuffers.
//
// FlatBuffers is a zero-copy serialization format. Unlike other codecs
// (JSON, Protobuf, etc.), FlatBuffers does not have a generic Marshal/Unmarshal
// API — serialization requires a generated Builder and deserialization requires
// a generated type that implements flatbuffers.FlatBuffer.
//
// To bridge this with the encoding.Codec interface, this package expects:
//   - Marshal:   the value must implement [FlatBufferMarshaler].
//   - Unmarshal: the target must implement [flatbuffers.FlatBuffer].
//
// The codec self-registers under the name "flatbuffers" via init().
package flatbuffers

import (
	"fmt"

	fb "github.com/google/flatbuffers/go"

	"github.com/tx7do/go-wind-plugins/encoding"
)

// Name is the name registered for the FlatBuffers codec.
const Name = "flatbuffers"

func init() {
	encoding.RegisterCodec(codec{})
}

// FlatBufferMarshaler is implemented by generated FlatBuffer types to produce
// a serialized buffer. Typically, the flatc compiler generates a
// Pack() or similar method that writes into a flatbuffers.Builder.
type FlatBufferMarshaler interface {
	// Pack builds the FlatBuffer and returns the finished bytes.
	PackFlatBuffer() ([]byte, error)
}

// codec implements encoding.Codec using Google FlatBuffers.
type codec struct{}

// Marshal encodes v into FlatBuffer bytes.
// v must implement [FlatBufferMarshaler].
func (codec) Marshal(v any) ([]byte, error) {
	m, ok := v.(FlatBufferMarshaler)
	if !ok {
		return nil, fmt.Errorf("flatbuffers: value %T does not implement FlatBufferMarshaler", v)
	}
	return m.PackFlatBuffer()
}

// Unmarshal decodes FlatBuffer data into v.
// v must be a pointer to a type that implements [flatbuffers.FlatBuffer]
// (i.e. has an Init method generated by flatc).
func (codec) Unmarshal(data []byte, v any) error {
	t, ok := v.(fb.FlatBuffer)
	if !ok {
		return fmt.Errorf("flatbuffers: target %T does not implement flatbuffers.FlatBuffer", v)
	}
	fb.GetRootAs(data, 0, t)
	return nil
}

// Name returns the codec name.
func (codec) Name() string {
	return Name
}
