// Package main demonstrates a GraphQL server that reuses the same HTTP middleware
// (recovery, request-id, logging) as the standard HTTP server.
//
// GraphQL runs over HTTP, so the transport/graphql package uses a type alias
// for Middleware (= func(http.Handler) http.Handler), allowing all
// transport/http/middleware packages to be applied directly without any adapter.
//
// Run:
//
//	go run ./examples/graphql-basic
//
// Test:
//
//	curl -X POST http://localhost:8080/query \
//	  -H "Content-Type: application/json" \
//	  -d '{"query":"{ hygrothermograph { humidity temperature } }"}'
//
// You can also visit http://localhost:8080/ to try the interactive Playground.
package main

import (
	"context"
	"fmt"
	"math/rand"
	"os"
	"os/signal"
	"syscall"

	graphqlAPI "github.com/tx7do/go-wind-plugins/testing/api/graphql"
	graphqlServer "github.com/tx7do/go-wind-plugins/transport/graphql"
	"github.com/tx7do/go-wind-plugins/transport/http/middleware/logging"
	"github.com/tx7do/go-wind-plugins/transport/http/middleware/recovery"
	"github.com/tx7do/go-wind-plugins/transport/http/middleware/requestid"

	"github.com/99designs/gqlgen/graphql/playground"
)

// resolver implements both ResolverRoot and QueryResolver generated by gqlgen.
type resolver struct{}

// Query returns the QueryResolver. Required by ResolverRoot.
func (r *resolver) Query() graphqlAPI.QueryResolver { return r }

// Hygrothermograph returns a random temperature & humidity reading.
func (r *resolver) Hygrothermograph(_ context.Context) (*graphqlAPI.Hygrothermograph, error) {
	return &graphqlAPI.Hygrothermograph{
		Humidity:    float64(rand.Intn(100)),
		Temperature: float64(rand.Intn(40)),
	}, nil
}

func main() {
	srv := graphqlServer.NewServer(":8080")

	// ── Middleware chain ─────────────────────────────────────────────
	// These are the SAME middleware packages used by transport/http.
	// Thanks to the type alias (Middleware = func(http.Handler) http.Handler),
	// they can be passed directly to the GraphQL server without any adapter.
	srv.Use(
		recovery.Middleware(),
		requestid.Middleware(),
		logging.Middleware(),
	)

	// Register the GraphQL schema at /query.
	schema := graphqlAPI.NewExecutableSchema(graphqlAPI.Config{
		Resolvers: &resolver{},
	})
	srv.Handle("/query", schema)

	// Optional: GraphQL Playground (interactive IDE) at the root path.
	srv.HandleFunc("/", playground.Handler("GraphQL Playground", "/query"))

	// Graceful shutdown.
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	fmt.Printf("GraphQL server listening on %s\n", srv.Endpoint())
	fmt.Println("  Playground: http://localhost:8080/")
	fmt.Println("  Endpoint:   http://localhost:8080/query")

	if err := srv.Start(ctx); err != nil {
		fmt.Fprintf(os.Stderr, "server error: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("server stopped")
}
