package thrift_test

import (
	"context"
	"fmt"

	"github.com/apache/thrift/lib/go/thrift"

	"github.com/tx7do/go-wind-plugins/encoding"
	_ "github.com/tx7do/go-wind-plugins/encoding/thrift" // register the Thrift codec used for message payloads
)

// sampleMessage is a minimal stand-in for a struct generated by the Thrift
// compiler: it implements thrift.TStruct by writing and reading a single
// string field through the binary protocol, which is the only message shape
// the codec accepts.
type sampleMessage struct {
	Name string
}

func (m *sampleMessage) Write(ctx context.Context, p thrift.TProtocol) error {
	if err := p.WriteStructBegin(ctx, "sampleMessage"); err != nil {
		return err
	}
	if err := p.WriteFieldBegin(ctx, "Name", thrift.STRING, 1); err != nil {
		return err
	}
	if err := p.WriteString(ctx, m.Name); err != nil {
		return err
	}
	if err := p.WriteFieldEnd(ctx); err != nil {
		return err
	}
	if err := p.WriteFieldStop(ctx); err != nil {
		return err
	}
	return p.WriteStructEnd(ctx)
}

func (m *sampleMessage) Read(ctx context.Context, p thrift.TProtocol) error {
	if _, err := p.ReadStructBegin(ctx); err != nil {
		return err
	}
	for {
		_, fieldType, fieldID, err := p.ReadFieldBegin(ctx)
		if err != nil {
			return err
		}
		if fieldType == thrift.STOP {
			break
		}
		if fieldID == 1 && fieldType == thrift.STRING {
			if m.Name, err = p.ReadString(ctx); err != nil {
				return err
			}
		}
		if err := p.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	return p.ReadStructEnd(ctx)
}

// Example resolves the Thrift codec through the shared codec registry and
// round-trips a message through it. Thrift serialization is driven by
// TStruct implementations that the Thrift compiler normally generates, so
// the sample type above plays that role with one hand-written string field.
func Example() {
	codec := encoding.GetCodec("thrift")
	if codec == nil {
		return
	}

	encoded, err := codec.Marshal(&sampleMessage{Name: "hello"})
	if err != nil {
		return
	}

	decoded := &sampleMessage{}
	if err := codec.Unmarshal(encoded, decoded); err != nil {
		return
	}

	fmt.Println(decoded.Name)
	// Output: hello
}
