// Package thrift provides a [encoding.Codec] implementation using
// Apache Thrift's binary protocol.
//
// Thrift is a binary serialization format originally developed at Facebook
// and now maintained by the Apache Software Foundation. It is widely used
// in high-performance RPC frameworks (e.g. CloudWeGo Kitex, Apache Thrift).
//
// The codec self-registers under the name "thrift" via init().
//
// Note: Thrift serialization requires the value to implement
// thrift.TStruct (i.e. have Read/Write methods generated by the Thrift
// compiler). Plain Go structs without generated code will return an error.
package thrift

import (
	"context"
	"fmt"

	"github.com/apache/thrift/lib/go/thrift"

	"github.com/tx7do/go-wind-plugins/encoding"
)

// Name is the name registered for the Thrift codec.
const Name = "thrift"

func init() {
	encoding.RegisterCodec(codec{})
}

// codec implements encoding.Codec using Apache Thrift binary protocol.
type codec struct {
	serializer   *thrift.TSerializer
	deserializer *thrift.TDeserializer
}

// Marshal encodes v into Thrift binary bytes.
// v must implement thrift.TStruct (i.e. be a generated Thrift struct).
func (c codec) Marshal(v any) ([]byte, error) {
	t, ok := v.(thrift.TStruct)
	if !ok {
		return nil, fmt.Errorf("thrift: value %T does not implement thrift.TStruct", v)
	}
	s := c.serializer
	if s == nil {
		s = thrift.NewTSerializer()
	}
	return s.Write(context.Background(), t)
}

// Unmarshal decodes Thrift binary data into v.
// v must be a pointer to a type that implements thrift.TStruct.
func (c codec) Unmarshal(data []byte, v any) error {
	t, ok := v.(thrift.TStruct)
	if !ok {
		return fmt.Errorf("thrift: target %T does not implement thrift.TStruct", v)
	}
	d := c.deserializer
	if d == nil {
		d = thrift.NewTDeserializer()
	}
	return d.Read(context.Background(), t, data)
}

// Name returns the codec name.
func (codec) Name() string {
	return Name
}
