// Package validate provides gRPC server interceptors that validate incoming
// request messages. Messages that implement the [Validator] interface (typically
// generated by protoc-gen-validate) are validated before the handler is
// invoked. Invalid requests are rejected with codes.InvalidArgument.
//
// This is the gRPC counterpart of transport/http/middleware/validate. While
// the HTTP middleware validates request-level concerns (body size, content
// type, headers), this interceptor validates the protobuf message itself.
//
// Usage:
//
//	srv := grpc.NewServer(grpc.ChainUnaryInterceptor(
//	    grpcValidate.UnaryServerInterceptor(),
//	))
package validate

import (
	"context"
	"fmt"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// Validator is the interface that protobuf messages implement when generated
// with validation rules (e.g. via protoc-gen-validate).
//
// The generated code implements this interface with a method like:
//
//	func (m *MyMessage) Validate() error { ... }
type Validator interface {
	Validate() error
}

// ValidatorFunc is a function type that validates a request message.
// It can be used to register custom validation logic for messages that
// do not implement the [Validator] interface natively.
type ValidatorFunc func(req any) error

// Option configures the validate interceptors.
type Option func(*options)

type options struct {
	// customValidators maps message type names to custom validator functions.
	// This allows validating messages that do not implement [Validator].
	customValidators map[string]ValidatorFunc

	// skipMethods is a set of full method names to skip validation.
	skipMethods map[string]bool
}

// WithValidator registers a custom validator function for a specific message
// type. The typeName should match the result of fmt.Sprintf("%T", msg).
func WithValidator(typeName string, fn ValidatorFunc) Option {
	return func(o *options) {
		if o.customValidators == nil {
			o.customValidators = make(map[string]ValidatorFunc)
		}
		o.customValidators[typeName] = fn
	}
}

// WithSkipMethod adds method names (full gRPC method paths like
// "/pkg.Service/Method") that should bypass validation.
func WithSkipMethod(methods ...string) Option {
	return func(o *options) {
		if o.skipMethods == nil {
			o.skipMethods = make(map[string]bool)
		}
		for _, m := range methods {
			o.skipMethods[m] = true
		}
	}
}

// UnaryServerInterceptor returns a [grpc.UnaryServerInterceptor] that validates
// incoming unary request messages. If the message implements [Validator],
// its Validate method is called. Validation failures return
// codes.InvalidArgument.
func UnaryServerInterceptor(opts ...Option) grpc.UnaryServerInterceptor {
	cfg := &options{}
	for _, opt := range opts {
		opt(cfg)
	}

	return func(
		ctx context.Context,
		req any,
		info *grpc.UnaryServerInfo,
		handler grpc.UnaryHandler,
	) (any, error) {
		if cfg.skipMethods[info.FullMethod] {
			return handler(ctx, req)
		}

		if err := validateMessage(req, cfg); err != nil {
			return nil, status.Error(codes.InvalidArgument, err.Error())
		}

		return handler(ctx, req)
	}
}

// StreamServerInterceptor returns a [grpc.StreamServerInterceptor] that
// validates incoming streaming request messages. Each message received through
// the stream is validated before being forwarded to the handler.
func StreamServerInterceptor(opts ...Option) grpc.StreamServerInterceptor {
	cfg := &options{}
	for _, opt := range opts {
		opt(cfg)
	}

	return func(
		srv any,
		ss grpc.ServerStream,
		info *grpc.StreamServerInfo,
		handler grpc.StreamHandler,
	) error {
		wrapped := &validatingStream{ServerStream: ss, cfg: cfg}
		return handler(srv, wrapped)
	}
}

// validateMessage checks if req implements Validator or has a custom
// validator registered. Returns nil if no validation is applicable.
func validateMessage(req any, cfg *options) error {
	// Try built-in Validator interface first.
	if v, ok := req.(Validator); ok {
		return v.Validate()
	}

	// Try custom validators by type name.
	if cfg.customValidators != nil {
		typeName := typeName(req)
		if fn, ok := cfg.customValidators[typeName]; ok {
			return fn(req)
		}
	}

	return nil
}

// typeName returns the Go type name of the given value.
func typeName(v any) string {
	if v == nil {
		return ""
	}
	return fmt.Sprintf("%T", v)
}

// ---------------------------------------------------------------------------
// validatingStream wraps a grpc.ServerStream to validate each message.
// ---------------------------------------------------------------------------

type validatingStream struct {
	grpc.ServerStream
	cfg *options
}

func (s *validatingStream) SendMsg(m any) error {
	return s.ServerStream.SendMsg(m)
}

func (s *validatingStream) RecvMsg(m any) error {
	if err := s.ServerStream.RecvMsg(m); err != nil {
		return err
	}
	if err := validateMessage(m, s.cfg); err != nil {
		return status.Error(codes.InvalidArgument, err.Error())
	}
	return nil
}
